# Generated by Django 3.2.12 on 2022-03-03 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
